apiVersion: apps/v1
kind: Deployment

metadata:
  name: nityaagarwal-deployment
  namespace: mc-lab
  labels:
    user: nityaagarwal

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
       #nodeSelector:
        # kubernetes.io/hostname: k8s-haosu-10.sdsc.optiputer.net
      containers:
      - name: container
        image: jerrypiglet/rui_conda_inverse:public
        args: ["sleep", "infinity"]
        resources:  
          requests:
            cpu: "25" # "100"
            memory: "40Gi" #"2Gi"
            nvidia.com/gpu: 2
          limits:
            cpu: "45" #"16" 
            memory: "70Gi" #"16Gi"
            nvidia.com/gpu: 2
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: openroomsindept
          mountPath: /openroomsindept
        - name: nityaagarwaldata
          mountPath: /nityaagarwaldata

      volumes:
      - name: nityaagarwaldata
        persistentVolumeClaim:
            claimName: nityaagarwaldata
      - name: openroomsindept
        persistentVolumeClaim:
            claimName: openroomsindept
      - name: dshm
        emptyDir:
          medium: Memory

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                - haosu
